<a href="https://colab.research.google.com/github/prernakakuniya2207/PythonLabAssignments/blob/main/4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# --- a) Generate a 4x4 Identity Matrix ---
print("--- (a) 4x4 Identity Matrix ---")
identity_matrix = np.eye(4)
print(identity_matrix)

# --- b) 3x3 Random Matrices & Operations ---
print("\n--- (b) Random 3x3 Matrix Operations ---")

# Generate two 3x3 matrices with random integers from 1 to 9
matrix_a = np.random.randint(1, 10, (3, 3))
matrix_b = np.random.randint(1, 10, (3, 3))

print("Matrix A:\n", matrix_a)
print("Matrix B:\n", matrix_b)

# Matrix Addition
addition = matrix_a + matrix_b
print("\nMatrix Addition (A + B):\n", addition)

# Matrix Multiplication (Dot Product)
multiplication = np.dot(matrix_a, matrix_b)
print("\nMatrix Multiplication (A x B):\n", multiplication)


--- (a) 4x4 Identity Matrix ---
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

--- (b) Random 3x3 Matrix Operations ---
Matrix A:
 [[6 9 9]
 [6 5 9]
 [2 9 8]]
Matrix B:
 [[8 9 1]
 [8 6 6]
 [2 7 5]]

Matrix Addition (A + B):
 [[14 18 10]
 [14 11 15]
 [ 4 16 13]]

Matrix Multiplication (A x B):
 [[138 171 105]
 [106 147  81]
 [104 128  96]]


In [2]:
import numpy as np

def get_matrix_input(rows, cols, name):
    print(f"\nEnter {rows*cols} elements for Matrix {name} ({rows}x{cols}):")
    # Take space-separated inputs and reshape into the target dimensions
    elements = list(map(float, input().split()))
    if len(elements) != rows * cols:
        print(f"❌ Error: Expected {rows*cols} elements, but got {len(elements)}.")
        return None
    return np.array(elements).reshape(rows, cols)

# 1. Define dimensions
# Matrix A: 5x3 | Matrix B: 3x2
mat_a = get_matrix_input(5, 3, "A")
mat_b = get_matrix_input(3, 2, "B")

if mat_a is not None and mat_b is not None:
    # 2. Perform Multiplication
    # Dot product of (5x3) and (3x2) results in a (5x2) matrix
    product_matrix = np.matmul(mat_a, mat_b)

    # 3. Print Results
    print("\n--- Matrix A (5x3) ---")
    print(mat_a)
    print("\n--- Matrix B (3x2) ---")
    print(mat_b)
    print("\n--- Resulting Product Matrix (5x2) ---")
    print(product_matrix)


Enter 15 elements for Matrix A (5x3):
26
❌ Error: Expected 15 elements, but got 1.

Enter 6 elements for Matrix B (3x2):
5
❌ Error: Expected 6 elements, but got 1.
